#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';
require_once 'yard.php';

use \app\core\src\console\ConsoleCommand;

$method = ($argv[1] ?? 'run') === 'help' ? 'help' : 'run';

(new ConsoleCommand($argv))->{$method}();