<?php

/*******************************
 * Bootstrap Controller 
 * AUTHOR: RE_WEB
 * @package app\core\Controller
*/

namespace app\core;

use \app\core\middlewares\Middleware;
use \app\core\exceptions\NotFoundException;

class Controller {

    private const DEFAULT_METHOD = 'index';
    private const INVALID_METHOD_TEXT = 'Invalid method';
    private const INVALID_CONTROLLER_TEXT = 'Invalid controller';

    /**
     * @var string $currentAction
    */

    public string $action = '';

    /**
     * @var array Variable data generated by extending controllers.
    */

    protected $data = [];

    /*
     * Default layout
    */

    public string $layout = 'main';

    /*
     * Support for additional controller logic, partials
    */

    protected array $children = [];

    /**
     * Set data in current controller
     * @return void
    */

    public function setData(array $data): void {
        array_merge($this->data, $data);
    }
    
    /**
     * Array of middleware classes
     * @var app\core\middlewares\Middleware[]
    */

    protected array $middlewares = [];

    /**
     * Set child data with corresponding controller/method
    */

    protected function setChildData(array $childControllers) {
        foreach ( $childControllers as $childController ) {
            [$controller, $method] = preg_match('/:/', $childController) ? explode(':', $childController) : [$childController, self::DEFAULT_METHOD];
            $childController = '\\app\controllers\\'.$controller.'Controller';
            if (!class_exists($controller)) throw new NotFoundException(self::INVALID_CONTROLLER_TEXT);
            if (!method_exists($controller, $method)) throw new NotFoundException(self::INVALID_METHOD_TEXT);
            $this->setData((new $controller())->{$method}());
        }
    }

    /**
     * Get names of children controllers
     * @return array
    */

    public function getChildren() : array {
        return $this->children;
    }

    /**
        * @return string
    */

    public function getTemplatePath(string $template): string {
        $view = Application::$ROOT_DIR.'view/partials/'.$template.'.tpl.php';
        return $view;
    }

    public function render(string $view, array $params = []) {
        echo Application::$app->view->renderView($view, $params);
    }

    public function setLayout(string $layout) {
        $this->layout = $layout;
    }

    public function registerMiddleware(Middleware $middleware) {
        $this->middlewares[] = $middleware;
    }   

    public function getMiddlewares(): array {
        return $this->middlewares;
    }

}